### ISSUE TITLE
ArrayIndexOutOfBoundsException when joining server

### ISSUE THREAD

**Issue by Sulfatezzz** [NukkitX/Nemisys#10]
`20:45:36 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 5027
        at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
        at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
        at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
        at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:270)
        at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:252)
        at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:261)
        at org.itxtech.nemisys.network.protocol.mcpe.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:50)
        at org.itxtech.nemisys.Client.handleDataPacket(Client.java:176)
        at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:112)
        at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:83)
        at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:103)
        at org.itxtech.nemisys.Server.tick(Server.java:458)
        at org.itxtech.nemisys.Server.tickProcessor(Server.java:425)
        at org.itxtech.nemisys.Server.start(Server.java:405)
        at org.itxtech.nemisys.Server.<init>(Server.java:201)
        at org.itxtech.nemisys.Nemisys.main(Nemisys.java:53)`

**Comment by SupremeMortal** [comment]
Is this fixed by the latest commit @Sulfatezzz ?

**Comment by Sulfatezzz** [comment]
Randomly after sending a player from Server A to B this happen
[ALERT] java.lang.ArrayIndexOutOfBoundsException: 247
        at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
        at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
        at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
        at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:270)
        at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:252)
        at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:261)
        at org.itxtech.nemisys.network.protocol.mcpe.AddPlayerPacket.decode(AddPlayerPacket.java:35)
        at org.itxtech.nemisys.Player.processIncomingBatch(Player.java:398)
        at org.itxtech.nemisys.Player.handleIncomingPacket(Player.java:180)
        at org.itxtech.nemisys.Player.onUpdate(Player.java:259)
        at org.itxtech.nemisys.Server.lambda$tick$2(Server.java:469)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Sulfatezzz** [comment]
Yes only happens when you sending a player from server x to server y. Not on the main server for some reasons
