### ISSUE TITLE
ArrayIndexOutOfBoundsException (returns)

### ISSUE THREAD

**Issue by Sulfatezzz** [NukkitX/Nemisys#11]
Occurs randomly on joining 

17:59:08 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 247
        at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
        at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
        at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
        at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:270)
        at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:252)
        at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:261)
        at org.itxtech.nemisys.network.protocol.mcpe.AddPlayerPacket.decode(AddPlayerPacket.java:35)
        at org.itxtech.nemisys.Player.processIncomingBatch(Player.java:398)
        at org.itxtech.nemisys.Player.handleIncomingPacket(Player.java:180)
        at org.itxtech.nemisys.Player.onUpdate(Player.java:259)
        at org.itxtech.nemisys.Server.lambda$tick$2(Server.java:469)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by SupremeMortal** [comment]
Does this still occur?
