### ISSUE TITLE
rideable entity bug

### ISSUE THREAD

**Issue by wode490390** [NukkitX/Nemisys#12]
Player cannot enter minecart and boat

**Comment by Creeperface01** [comment]
Plese provide full stack trace

**Comment by FJackZhou** [comment]
[root@iz1y7s3osjqxnwz ~]# jstack 5898
2018-10-26 22:38:35
Full thread dump OpenJDK 64-Bit Server VM (25.181-b13 mixed mode):

"pool-2-thread-1" #35 prio=5 os_prio=0 tid=0x00007fb68898a000 nid=0x17c3 waiting on condition [0x00007fb64e856000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066b70bcf8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-3-thread-1" #33 prio=5 os_prio=0 tid=0x00007fb688a19000 nid=0x17b6 waiting on condition [0x00007fb64e957000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066b70bdb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Nukkit Asynchronous Task Handler #3" #32 daemon prio=5 os_prio=0 tid=0x00007fb68895c800 nid=0x17b5 waiting on condition [0x00007fb64ea58000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066ad6ed18> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"process reaper" #31 daemon prio=10 os_prio=0 tid=0x00007fb65000b000 nid=0x17b4 waiting on condition [0x00007fb678081000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066ac5b480> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Nukkit Asynchronous Task Handler #2" #30 daemon prio=5 os_prio=0 tid=0x00007fb688a17000 nid=0x177d waiting on condition [0x00007fb64ed59000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066ad6ed18> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Nukkit Asynchronous Task Handler #1" #29 daemon prio=5 os_prio=0 tid=0x00007fb688a16000 nid=0x177c waiting on condition [0x00007fb656312000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066ad6ed18> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Attach Listener" #27 daemon prio=9 os_prio=0 tid=0x00007fb660007800 nid=0x1773 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Nukkit Asynchronous Task Handler #0" #25 daemon prio=5 os_prio=0 tid=0x00007fb6888b3000 nid=0x172b waiting on condition [0x00007fb65450b000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000066ad6ed18> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Thread-9" #24 prio=5 os_prio=0 tid=0x00007fb6888ae800 nid=0x172a in Object.wait() [0x00007fb65460c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066b70c8c8> (a cn.nukkit.utils.Watchdog)
	at cn.nukkit.utils.Watchdog.run(Watchdog.java:58)
	- locked <0x000000066b70c8c8> (a cn.nukkit.utils.Watchdog)

"threadDeathWatcher-4-1" #23 daemon prio=1 os_prio=0 tid=0x00007fb65c4a2000 nid=0x1728 waiting on condition [0x00007fb655b0e000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

"nioEventLoopGroup-3-1" #22 prio=10 os_prio=0 tid=0x000000000078a000 nid=0x1727 runnable [0x00007fb655c0f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000066b70ce10> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000066b70ce00> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000066b70cdb8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

"SynapseAPI Async Ticker" #20 prio=5 os_prio=0 tid=0x00007fb688754800 nid=0x1726 waiting on condition [0x00007fb655d10000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.itxtech.synapseapi.SynapseEntry$AsyncTicker.run(SynapseEntry.java:215)
	at java.lang.Thread.run(Thread.java:748)

"SynLib Client Thread #19" #19 prio=5 os_prio=0 tid=0x00007fb688752000 nid=0x1725 waiting on condition [0x00007fb657ffe000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.itxtech.synapseapi.network.synlib.Session.tickProcessor(Session.java:50)
	at org.itxtech.synapseapi.network.synlib.Session.run(Session.java:34)
	at org.itxtech.synapseapi.network.synlib.SynapseClient.run(SynapseClient.java:132)

"Abandoned connection cleanup thread" #16 daemon prio=5 os_prio=0 tid=0x00007fb688573800 nid=0x1721 in Object.wait() [0x00007fb657af1000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066b59fc40> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000066b59fc40> (a java.lang.ref.ReferenceQueue$Lock)
	at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Console" #9 prio=5 os_prio=0 tid=0x00007fb688347000 nid=0x171d runnable [0x00007fb6647e5000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	- locked <0x000000066ac94d30> (a jline.internal.NonBlockingInputStream)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	- locked <0x000000066ac94d30> (a jline.internal.NonBlockingInputStream)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	- locked <0x000000066ac94d30> (a jline.internal.NonBlockingInputStream)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2151)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2141)
	at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2226)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2467)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
	at cn.nukkit.command.CommandReader.run(CommandReader.java:63)

"NonBlockingInputStreamThread" #12 daemon prio=5 os_prio=0 tid=0x00007fb688306800 nid=0x171c in Object.wait() [0x00007fb6648e6000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066ac94d30> (a jline.internal.NonBlockingInputStream)
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	- locked <0x000000066ac94d30> (a jline.internal.NonBlockingInputStream)
	at java.lang.Thread.run(Thread.java:748)

"Logger" #8 prio=5 os_prio=0 tid=0x00007fb68827a800 nid=0x1714 in Object.wait() [0x00007fb6649e7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066ab2d580> (a cn.nukkit.utils.MainLogger)
	at cn.nukkit.utils.MainLogger.waitForMessage(MainLogger.java:229)
	- locked <0x000000066ab2d580> (a cn.nukkit.utils.MainLogger)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:165)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007fb688140800 nid=0x1712 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007fb68813b800 nid=0x1711 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007fb688139000 nid=0x1710 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fb68812c800 nid=0x170f runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fb688100800 nid=0x170e in Object.wait() [0x00007fb678283000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066aaa7e58> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000066aaa7e58> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fb6880fc000 nid=0x170d in Object.wait() [0x00007fb678384000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000066aaa64d0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000066aaa64d0> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007fb68804b000 nid=0x170b waiting on condition [0x00007fb690e2b000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at cn.nukkit.Server.tickProcessor(Server.java:876)
	at cn.nukkit.Server.start(Server.java:830)
	at cn.nukkit.Server.<init>(Server.java:513)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)

"VM Thread" os_prio=0 tid=0x00007fb6880f2800 nid=0x170c runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fb688143000 nid=0x1713 waiting on condition 

JNI global references: 435

[root@iz1y7s3osjqxnwz ~]#

**Comment by wode490390** [comment]
no errors

**Comment by PetteriM1** [comment]
Isn't this already fixed?
