### ISSUE TITLE
Problems with latest builds

### ISSUE THREAD

**Issue by IanPedroV** [NukkitX/Nemisys#2]
When using the lastest version of this project, in the master branch, when a player tries do join in the server this error pops up: 

2018-4-25 18:48:43 [INFO] Loading server properties...
2018-4-25 18:48:43 [INFO] Selected English (eng) as the base language
2018-4-25 18:48:43 [INFO] Starting Minecraft: PE server version v1.2.2
2018-4-25 18:48:43 [INFO] Opening server on 0.0.0.0:19132
2018-4-25 18:48:43 [INFO] This server is running Nemisys version 2.0dev "Aegis" (API 1.0.6)
2018-4-25 18:48:43 [INFO] Nemisys is distributed under the LGPL License
2018-4-25 18:48:43 [INFO] Loading fmcnemisyspunisher v1.0.0
2018-4-25 18:48:43 [INFO] Loading FMCPocketNemisys v1.0.0
2018-4-25 18:48:43 [INFO] Enabling fmcnemisyspunisher v1.0.0
2018-4-25 18:48:43 [INFO] [fmcnemisyspunisher] Enabling fmcnemisys: PUNISHER
2018-4-25 18:48:43 [INFO] Enabling FMCPocketNemisys v1.0.0
2018-4-25 18:48:43 [INFO] [FMCPocketNemisys] Enabling fmcnemisys: CORE
2018-4-25 18:48:43 [INFO] Starting GS4 status listener
2018-4-25 18:48:43 [INFO] Setting query port to 19132
2018-4-25 18:48:43 [INFO] Query running on 0.0.0.0:19132
2018-4-25 18:48:43 [INFO] Done (0.657s)! For help, type "help" or "?"
2018-4-25 18:48:46 [NOTICE] Client 127.0.0.1:55890 has connected successfully
2018-4-25 18:48:46 [NOTICE] mainServer: true
2018-4-25 18:48:46 [NOTICE] description: FMC_mainlobby
2018-4-25 18:48:46 [NOTICE] maxPlayers: 20
2018-4-25 18:48:46 [NOTICE] Client 127.0.0.1:55923 has connected successfully
2018-4-25 18:48:46 [NOTICE] mainServer: false
2018-4-25 18:48:46 [NOTICE] description: FMC_arenaserver1
2018-4-25 18:48:46 [NOTICE] maxPlayers: 20
2018-4-25 18:48:59 [CRITICAL] [Network] Stopped interface org.itxtech.nemisys.network.RakNetInterface due to 
`
`

When using the latest version of the v2.0 branch, and also every commit after d8faef10283b945c4614946a33d9cb90ae74c00f (master branch), except the the last commit, this error pops up when a player is transfered: 

`
# transfering to main server
2018-4-25 19:58:55 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 4789
	at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
	at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
	at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
	at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:270)
	at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:252)
	at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:261)
	at org.itxtech.nemisys.network.protocol.mcpe.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:91)
	at org.itxtech.nemisys.Client.handleDataPacket(Client.java:176)
	at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:112)
	at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:83)
	at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:103)
	at org.itxtech.nemisys.Server.tick(Server.java:449)
	at org.itxtech.nemisys.Server.tickProcessor(Server.java:420)
	at org.itxtech.nemisys.Server.start(Server.java:400)
	at org.itxtech.nemisys.Server.<init>(Server.java:196)
	at org.itxtech.nemisys.Nemisys.main(Nemisys.java:53)
# transfering to other server
2018-4-25 20:00:21 [INFO] FouzerGamer has been transferred to FMC_arenaserver1
2018-4-25 20:00:21 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 4602
	at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
	at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
	at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
	at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:270)
	at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:252)
	at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:261)
	at org.itxtech.nemisys.network.protocol.mcpe.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:91)
	at org.itxtech.nemisys.Client.handleDataPacket(Client.java:176)
	at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:112)
	at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:83)
	at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:103)
	at org.itxtech.nemisys.Server.tick(Server.java:449)
	at org.itxtech.nemisys.Server.tickProcessor(Server.java:420)
	at org.itxtech.nemisys.Server.start(Server.java:400)
	at org.itxtech.nemisys.Server.<init>(Server.java:196)
	at org.itxtech.nemisys.Nemisys.main(Nemisys.java:53)
`

When using d8faef10283b945c4614946a33d9cb90ae74c00f (master) with the compatible SynapseAPI version everything works fine, apart from the fact that the org.itxtech.nemisys.Player.getUuid() method does not exist, that being the entire reason for me to have made the update.

**Comment by Creeperface01** [comment]
Do you have latest nukkit?

**Comment by IanPedroV** [comment]
Yes, I do.
