### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MasterLuke117** [NukkitX/Nemisys#22]
was testing the official Nemisys server today with the latest build, was getting this error on every startup.

```
> 03:48:54 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 32
at org.itxtech.nemisys.utils.BinaryStream.getByte(BinaryStream.java:192)
at org.itxtech.nemisys.utils.VarInt.read(VarInt.java:50)
at org.itxtech.nemisys.utils.VarInt.readUnsignedVarInt(VarInt.java:95)
at org.itxtech.nemisys.utils.BinaryStream.getUnsignedVarInt(BinaryStream.java:272)
at org.itxtech.nemisys.utils.BinaryStream.getByteArray(BinaryStream.java:254)
at org.itxtech.nemisys.utils.BinaryStream.getString(BinaryStream.java:263)
at org.itxtech.nemisys.network.protocol.spp.ConnectPacket.decode(ConnectPacket.java:43)
at org.itxtech.nemisys.network.SynapseInterface.handlePacket(SynapseInterface.java:111)
at org.itxtech.nemisys.network.SynapseInterface.processPackets(SynapseInterface.java:83)
at org.itxtech.nemisys.network.SynapseInterface.process(SynapseInterface.java:103)
at org.itxtech.nemisys.Server.tick(Server.java:459)
at org.itxtech.nemisys.Server.tickProcessor(Server.java:426)
at org.itxtech.nemisys.Server.start(Server.java:406)
at org.itxtech.nemisys.Server.<init>(Server.java:202)
at org.itxtech.nemisys.Nemisys.main(Nemisys.java:53) ```

``` 
03:52:53 [INFO] master Iuke has been transferred to lobby
> 03:52:53 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 03:52:54 [ALERT] java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Creeperface01** [comment]
What synapse implementation do you use? And also show your synapse config.

**Comment by MasterLuke117** [comment]
Aha!!!!!  player name space issue!!!  it doesn't do it when you don't have a space in your name:

```
> 08:03:28 [INFO] master Iuke has been transferred to lobby
> 08:03:28 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 08:03:29 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 08:03:29 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 08:04:20 [INFO] master Iuke has been transferred to 2b2t
> 08:04:21 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 08:04:21 [ALERT] java.lang.ArrayIndexOutOfBoundsException
> 08:04:21 [ALERT] java.lang.ArrayIndexOutOfBoundsException
```

Config:

```
#Synapse API for Nukkit: config
disable-rak: false
enable: true

lobbies: 
  - "lobby"
  
entries:
  - server-ip: xx.xx.xx.xx
    server-port: 10305
    isMainServer: true
    isLobbyServer: true
    transferOnShutdown: true
    password: xxxxxxxxxxxxxxxxxxxxxx
    description: lobby
    autoConnect: true
```
