### ISSUE TITLE
Cannot be used in 1.6

### ISSUE THREAD

**Issue by xiaozha13** [NukkitX/Nemisys#9]
When the player enters the lobby server, the lobby server reports an error and cannot enter the server.
image:https://i.loli.net/2018/08/30/5b878143c66a7.png

I confirm that I use the latest Nukkit and Nemisys.

This is the error log:
2018-8-30 13:28:00 [NOTICE] Synapse Client has connected to 127.0.0.1:10305
2018-8-30 13:28:00 [NOTICE] [SynapseAPI] Connecting 127.0.0.1:10305
2018-8-30 13:28:00 [NOTICE] [SynapseAPI] Login success to 127.0.0.1:10305
2018-8-30 13:28:05 [CRITICAL] Exception while invoking run
java.lang.ArrayIndexOutOfBoundsException: 3
	at cn.nukkit.utils.Binary.readLInt(Binary.java:257)
	at cn.nukkit.utils.BinaryStream.getLInt(BinaryStream.java:125)
	at cn.nukkit.network.protocol.LoginPacket.decodeChainData(LoginPacket.java:56)
	at cn.nukkit.network.protocol.LoginPacket.decode(LoginPacket.java:42)
	at org.itxtech.synapseapi.SynapsePlayer.handleLoginPacket(SynapsePlayer.java:74)
	at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:253)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
	at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277)
	at cn.nukkit.Server.tick(Server.java:1084)
	at cn.nukkit.Server.tickProcessor(Server.java:853)
	at cn.nukkit.Server.start(Server.java:830)
	at cn.nukkit.Server.<init>(Server.java:513)
	at cn.nukkit.Nukkit.main(Nukkit.java:105)

**Comment by PetteriM1** [comment]
You need to update SynapseAPI plugin too

**Comment by xiaozha13** [comment]
The SynapseAPI I use is the latest version on Jenkins. @PetteriM1

**Comment by PetteriM1** [comment]
@xiaozha13 The 1.6 support pull request is not accepted yet so you have to compile it yourself or find jar from discord
